---
apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: todo-app
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"  
  MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
  MONGO_URI: mongodb://MONGO_ROOT_USER:MONGO_ROOT_PASSWORD@mongo:27017/todoapp?authSource=admin

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: todo-app
spec:
  serviceName: "mongo-headless"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  namespace: todo-app
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: todo-app
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
