name: CI/CD • Todo Service

on:
  workflow_dispatch:   # Manual trigger


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies & run tests
        run: |
          cd todo-service
          npm ci
          npm test

      - name: Authenticate to GCP
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build with Cloud Build
        run: |
          cd todo-service
          gcloud builds submit todo-service \
            --tag=gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-service:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy todo-service \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-service:${{ github.sha }} \
            --platform=managed \
            --region=${{ secrets.GCP_REGION || 'us-central1' }} \
            --allow-unauthenticated \
            --port=3001
